import type {
  DiagnosticRow,
  EvalCaseResult,
  GraphCluster,
  GraphEdge,
  GraphNode,
  GraphResponse,
  LogEntry,
  Paper,
  ProviderStatus,
  QueryPlan,
  RankedPaper,
  ResultsResponse,
  SearchJob,
  SearchRequest,
  SelectionResult,
  StageArtifactResponse,
  SystemStatus,
  WorkflowResult,
} from "../types/api";

export interface PaperExplorerItem {
  id: string;
  title: string;
  year: number;
  venue: string;
  authors: string;
  snippet: string;
}

const mockQueryPlan: QueryPlan = {
  original_query: "近五年关于多模态大模型在医学影像诊断中的最新进展有哪些？",
  language: "zh",
  query_type: "survey",
  research_topic: "多模态大模型在医学影像诊断中的研究进展",
  task: "survey_latest_work",
  methods: ["多模态对齐", "视觉指令微调", "放射学基础模型", "检索增强推荐"],
  datasets: ["MIMIC-CXR", "CheXpert", "SLAKE"],
  entities: ["医学影像", "胸片诊断", "临床问答"],
  time_range: { start_year: 2020, end_year: 2025 },
  venues: ["arXiv", "Nature Machine Intelligence", "MICCAI"],
  must_have_constraints: ["医学影像", "多模态大模型", "近五年"],
  nice_to_have_constraints: ["综述或综述相关", "高引用"],
  exclude_terms: ["通用图像分类"],
  expected_output: "top_papers",
  uncertainty: ["部分工作仍处于预印本阶段"],
};

const makePaper = (
  paperId: string,
  title: string,
  authors: string[],
  year: number,
  venue: string,
  citationCount: number,
  source: string,
  tags: string[],
): Paper => ({
  paper_id: paperId,
  title,
  abstract:
    "本文聚焦多模态大模型在医学影像理解、临床问答、检索增强诊断与评测框架中的最新进展，并系统梳理了数据集、训练范式与落地挑战。",
  year,
  venue,
  authors,
  doi: `10.48550/arXiv.${paperId.replace("P-", "24.")}`,
  arxiv_id: `2404.${paperId.replace("P-", "")}`,
  url: `https://example.org/papers/${paperId}`,
  citation_count: citationCount,
  source,
  retrieval_path: [
    "query_understanding",
    "query_expansion",
    "multi_source_retrieval",
    "reranking",
  ],
  references: ["P-00042", "P-00081"],
  citations: ["P-10021", "P-10032", "P-10078"],
  metadata: { tags, publisher: venue },
});

const makeSelection = (
  paperId: string,
  reason: string,
  level: SelectionResult["relevance_level"],
  score: number,
  matchedConstraints: string[],
): SelectionResult => ({
  paper_id: paperId,
  relevance_level: level,
  matched_constraints: matchedConstraints,
  missing_constraints: level === "medium" ? ["综述相关"] : [],
  evidence: [
    {
      field: "abstract",
      text: "The paper summarizes multimodal LLM methods for radiology, evaluation and downstream medical reasoning tasks.",
    },
    {
      field: "title",
      text: "标题直接覆盖 medical imaging、multimodal、LLM 等关键语义约束。",
    },
  ],
  reason,
  confidence: 0.82,
  is_validated: true,
  validation_notes: ["constraint_coverage=0.86", "evidence_score=0.81"],
  relevance_score: score,
  constraint_score: 0.86,
  evidence_score: 0.81,
  uncertainty: [],
});

const topPapersSeed = [
  {
    id: "P-00017",
    title: "A Survey on Multimodal Large Language Models for Medical Imaging",
    authors: ["Y. Zhang", "L. Han", "X. Li", "P. Gao", "J. Wang"],
    year: 2024,
    venue: "arXiv preprint",
    citation: 1210,
    source: "arXiv",
    reason:
      "覆盖医学影像、多模态大模型、近五年与综述入口四个核心约束，是理解该领域的高价值起点文献。",
    level: "high" as const,
    score: 0.871,
    diversity: 0.742,
    tags: ["Survey", "Multimodal", "LLM", "Medical Imaging", "Review"],
  },
  {
    id: "P-00042",
    title: "Med-PaLM M 2: Enhancing Medical Vision-Language Understanding",
    authors: ["S. Singhal", "A. Tu", "J. Gottschlich"],
    year: 2024,
    venue: "Nature Machine Intelligence",
    citation: 893,
    source: "OpenAlex",
    reason:
      "代表医疗多模态大模型的关键能力边界，兼具视觉理解、临床问答和高影响引用。",
    level: "high" as const,
    score: 0.845,
    diversity: 0.812,
    tags: ["Medical VLM", "Clinical QA", "Vision-Language"],
  },
  {
    id: "P-00081",
    title: "RadFM: Foundation Model for Radiology",
    authors: ["H. Chen", "D. Dou", "Y. Jin", "X. Li", "R. Xu"],
    year: 2023,
    venue: "Radiology: Artificial Intelligence",
    citation: 742,
    source: "Semantic Scholar",
    reason: "聚焦放射学基础模型，和当前 query 的应用场景高度贴合，适合作为方法层代表工作。",
    level: "high" as const,
    score: 0.814,
    diversity: 0.693,
    tags: ["Foundation Model", "Radiology", "Medical Imaging"],
  },
  {
    id: "P-00118",
    title: "CheXagent: Towards a Large Vision-Language Model for Chest X-ray Diagnosis",
    authors: ["W. Jin", "Z. Zhang", "Y. Pan", "S. Wang"],
    year: 2023,
    venue: "MICCAI",
    citation: 521,
    source: "OpenAlex",
    reason: "胸片诊断方向的代表性系统，补充临床任务层面的落地案例。",
    level: "medium" as const,
    score: 0.792,
    diversity: 0.671,
    tags: ["Chest X-ray", "Diagnosis", "Medical Imaging"],
  },
  {
    id: "P-00167",
    title: "LitSearch: A Retrieval Benchmark for Scientific Literature Search",
    authors: ["Q. Zhu", "Y. Wang", "Y. Shen"],
    year: 2024,
    venue: "arXiv",
    citation: 148,
    source: "Local Index",
    reason: "与 Scholar Agent 的检索评测能力直接相关，适合作为 benchmark 与方法验证基准。",
    level: "medium" as const,
    score: 0.768,
    diversity: 0.741,
    tags: ["Benchmark", "Retrieval", "Scientific Search"],
  },
  {
    id: "P-00192",
    title: "PaSa: An LLM Agent for Comprehensive Academic Paper Search",
    authors: ["Q. Zhu", "Y. Wang", "Y. Shen", "H. Huang"],
    year: 2024,
    venue: "arXiv",
    citation: 92,
    source: "Local Index",
    reason: "与本系统架构直接相关，适合在 Agent 检索、Query Expansion 和 Reranking 聚类中展示。",
    level: "medium" as const,
    score: 0.741,
    diversity: 0.722,
    tags: ["Agent", "Reranking", "Academic Search"],
  },
];

const rankedPapers: RankedPaper[] = topPapersSeed.map((item, index) => ({
  paper: makePaper(
    item.id,
    item.title,
    item.authors,
    item.year,
    item.venue,
    item.citation,
    item.source,
    item.tags,
  ),
  selection: makeSelection(item.id, item.reason, item.level, item.score, [
    "医学影像",
    "多模态大模型",
    "近五年",
    ...(item.tags.includes("Survey") ? ["综述/综述相关"] : []),
  ]),
  final_score: item.score,
  subscores: {
    LLM_Relevance: item.score,
    Constraint_Coverage: 0.86,
    Evidence_Completeness: 0.81,
    Source_Agreement: 0.75,
    Diversity_Graph_Prior: item.diversity,
    Authority: Math.min(item.citation / 1500, 1),
    Recency: 0.9,
    BGE_Reranker: 0.78,
  },
  rank: index + 1,
}));

const mockWorkflowResult: WorkflowResult = {
  original_query: mockQueryPlan.original_query,
  query_plan: mockQueryPlan,
  search_process: [
    {
      round_index: 1,
      search_goal: "Round 1: Query Understanding + Multi-source Retrieval",
      queries: [
        "multimodal medical imaging llm",
        "\"medical imaging\" \"multimodal large language model\"",
        "radiology foundation model survey",
        "vision-language radiology diagnosis",
      ],
      candidates_found: 5642,
      review_conclusion: "coverage=0.78, converged=false",
    },
    {
      round_index: 2,
      search_goal: "Round 2: Retrieval Expansion + Selection Refinement",
      queries: [
        "instruction tuning radiology multimodal",
        "medical imaging benchmark multimodal llm",
      ],
      candidates_found: 3217,
      review_conclusion: "coverage=0.92, converged=true",
    },
  ],
  highly_relevant_papers: rankedPapers.slice(0, 3),
  partially_relevant_papers: rankedPapers.slice(3, 6),
  supporting_papers: [],
  method_clusters: [
    {
      cluster_name: "多模态对齐",
      paper_ids: ["P-00017", "P-00042"],
      summary: "聚焦视觉-语言对齐与跨模态语义融合。",
    },
    {
      cluster_name: "放射学基础模型",
      paper_ids: ["P-00081", "P-00118"],
      summary: "围绕放射学基础模型与临床诊断展开。",
    },
    {
      cluster_name: "检索评测",
      paper_ids: ["P-00167", "P-00192"],
      summary: "关注检索基准、Agent 搜索与重排序策略。",
    },
  ],
  timeline: [
    { year: 2020, event: "医学视觉语言基准开始快速积累" },
    { year: 2022, event: "Radiology foundation model 进入快速发展期" },
    { year: 2024, event: "多模态 LLM 综述与 Agent 检索工作集中出现" },
  ],
  citation_graph: {
    nodes: rankedPapers.map((paper) => ({
      id: paper.paper.paper_id,
      title: paper.paper.title,
      relevance: paper.selection.relevance_level,
      score: paper.final_score,
    })),
    links: [
      { source: "P-00017", target: "P-00042", type: "references" },
      { source: "P-00017", target: "P-00081", type: "references" },
      { source: "P-00192", target: "P-00167", type: "references" },
    ],
  },
  recommendation_reasoning: rankedPapers.slice(0, 4).map((paper) => ({
    paper_id: paper.paper.paper_id,
    title: paper.paper.title,
    relevance: paper.selection.relevance_level,
    final_score: paper.final_score,
    strength: paper.selection.reason,
    evidence_score: 0.81,
    constraint_coverage: 0.86,
    penalty_multiplier: 1,
    validation_notes: paper.selection.validation_notes,
  })),
  agent_self_report: {
    strategy_summary:
      "系统通过 query understanding、query expansion、多源召回、reranking 与 synthesis 形成最终推荐报告。",
    gaps_identified: ["部分临床数据集相关工作仍主要以预印本形式发布。"],
    refinement_history: ["Round 1: broad retrieval", "Round 2: evidence-focused reranking"],
  },
  run_metrics: {
    search_queries_used: 14,
    retrieval_rounds_used: 2,
    candidate_pool_size: 5642,
    final_papers: 10,
    evidence_summaries: 32,
    llm_calls_used: 11,
    llm_elapsed_seconds: 8.2,
    api_calls_used: 26,
    token_estimate: 48200,
    elapsed_seconds: 18.7,
    cache_hits: 82,
    errors: [],
    component_metrics: [
      {
        component: "query_understanding",
        elapsed_seconds: 2.1,
        items_delta: 0,
        api_calls_delta: 0,
        api_calls_total: 0,
        llm_calls_delta: 2,
        llm_calls_total: 2,
        token_estimate_delta: 8300,
        token_estimate_total: 8300,
        cache_hits_delta: 0,
        cache_hits_total: 0,
        errors_delta: 0,
        errors_total: 0,
        search_queries_delta: 0,
        search_queries_total: 0,
        retrieval_rounds_delta: 0,
        retrieval_rounds_total: 0,
      },
      {
        component: "retrieval",
        elapsed_seconds: 4.7,
        items_delta: 5642,
        api_calls_delta: 12,
        api_calls_total: 12,
        llm_calls_delta: 0,
        llm_calls_total: 2,
        token_estimate_delta: 0,
        token_estimate_total: 8300,
        cache_hits_delta: 48,
        cache_hits_total: 48,
        errors_delta: 0,
        errors_total: 0,
        search_queries_delta: 14,
        search_queries_total: 14,
        retrieval_rounds_delta: 2,
        retrieval_rounds_total: 2,
      },
      {
        component: "ranking",
        elapsed_seconds: 5.1,
        items_delta: 50,
        api_calls_delta: 6,
        api_calls_total: 18,
        llm_calls_delta: 5,
        llm_calls_total: 7,
        token_estimate_delta: 18400,
        token_estimate_total: 26700,
        cache_hits_delta: 17,
        cache_hits_total: 65,
        errors_delta: 0,
        errors_total: 0,
        search_queries_delta: 0,
        search_queries_total: 14,
        retrieval_rounds_delta: 0,
        retrieval_rounds_total: 2,
      },
      {
        component: "synthesis",
        elapsed_seconds: 3.8,
        items_delta: 10,
        api_calls_delta: 8,
        api_calls_total: 26,
        llm_calls_delta: 4,
        llm_calls_total: 11,
        token_estimate_delta: 21500,
        token_estimate_total: 48200,
        cache_hits_delta: 17,
        cache_hits_total: 82,
        errors_delta: 0,
        errors_total: 0,
        search_queries_delta: 0,
        search_queries_total: 14,
        retrieval_rounds_delta: 0,
        retrieval_rounds_total: 2,
      },
    ],
  },
  dynamic_k_chosen: 10,
  expected_f1_curve: { 1: 0.34, 3: 0.49, 5: 0.57, 8: 0.62, 10: 0.65 },
  g_hat: 25.4,
  g_hat_scope: 25.4,
  g_hat_pool: 31.7,
  g_hat_visible: 18.1,
  low_confidence_uniform: false,
  p_floor: 0.212,
  tie_break_reason: "F_beta + logistic cutoff (k1=6, k2=10)",
  second_pass_triggered: true,
};

export const mockSearchRequest: SearchRequest = {
  query: mockQueryPlan.original_query,
  mode: "research",
  config: "local_full_pipeline.yaml",
  providers: ["Semantic Scholar", "OpenAlex", "arXiv", "Local Index"],
  retrieval_only: false,
  use_local_index: true,
};

export const mockSearchJob: SearchJob = {
  job_id: "search_20260630_1042",
  status: "succeeded",
  stage: "synthesis",
  progress: 100,
  elapsed_seconds: 18.7,
};

export const mockResultsResponse: ResultsResponse = {
  job_id: mockSearchJob.job_id,
  status: "succeeded",
  result: mockWorkflowResult,
  artifacts: {
    candidate_pool_size: 5642,
    selection_candidates_size: 200,
    ranked_papers_size: 50,
    final_output_size: 10,
  },
};

export const mockStageArtifacts: Record<string, StageArtifactResponse> = {
  query_plan: {
    stage: "query_plan",
    job_id: mockSearchJob.job_id,
    data: mockWorkflowResult.query_plan as unknown as Record<string, unknown>,
  },
  retrieval: {
    stage: "retrieval",
    job_id: mockSearchJob.job_id,
    data: {
      candidate_pool_size: 5642,
      deduped: 3217,
      top_sources: [
        { provider: "OpenAlex", hits: 2142 },
        { provider: "Semantic Scholar", hits: 1482 },
        { provider: "arXiv", hits: 957 },
        { provider: "Local Index", hits: 1061 },
      ],
    },
  },
  selection: {
    stage: "selection",
    job_id: mockSearchJob.job_id,
    data: {
      selection_candidates_size: 200,
      high_confidence: 32,
      medium_confidence: 78,
      rejected: 90,
    },
  },
  ranking: {
    stage: "ranking",
    job_id: mockSearchJob.job_id,
    data: {
      ranked_papers: rankedPapers.slice(0, 10),
    },
  },
  synthesis: {
    stage: "synthesis",
    job_id: mockSearchJob.job_id,
    data: {
      final_output_size: 10,
      clusters: mockWorkflowResult.method_clusters,
      timeline: mockWorkflowResult.timeline,
    },
  },
};

export const mockConfigs = [
  "local_full_pipeline.yaml",
  "effect_first.yaml",
  "high_recall.yaml",
  "live_fast.yaml",
];

export const mockProviders: ProviderStatus[] = [
  {
    name: "Semantic Scholar",
    enabled: true,
    available: true,
    source: "remote",
    latency_ms: 280,
    status: "healthy",
    notes: "主召回源",
  },
  {
    name: "OpenAlex",
    enabled: true,
    available: true,
    source: "remote",
    latency_ms: 340,
    status: "healthy",
    notes: "图谱与引用扩展",
  },
  {
    name: "arXiv",
    enabled: true,
    available: true,
    source: "remote",
    latency_ms: 180,
    status: "healthy",
    notes: "预印本补充",
  },
  {
    name: "Local Index",
    enabled: true,
    available: true,
    source: "local",
    latency_ms: 35,
    status: "healthy",
    notes: "本地索引已加载 1,248,731 条",
  },
];

export const mockSystemStatus: SystemStatus = {
  status: "ok",
  message: "系统正常，provider 连接正常。",
  mode: "research",
  config: "local_full_pipeline.yaml",
  cache_hit_rate: 82.6,
  local_index_ready: true,
  vector_index_ready: true,
  provider_count: { healthy: 4, total: 4 },
};

const makeDiagnosticRow = (paper: RankedPaper, stage: string, pass = true): DiagnosticRow => ({
  paper_id: paper.paper.paper_id,
  title: paper.paper.title,
  source: paper.paper.source,
  year: paper.paper.year,
  citation_count: paper.paper.citation_count,
  relevance: paper.selection.relevance_score ?? paper.final_score,
  stage,
  score: paper.final_score,
  pass,
  reason: paper.selection.reason,
});

export const mockEvalCaseResult: EvalCaseResult = {
  job_id: "eval_20260630_case_128",
  dataset: "MedEval-2024",
  case_index: 128,
  query: mockQueryPlan.original_query,
  gold: ["A Survey on Multimodal Large Language Models for Medical Imaging"],
  progress: [
    { stage: "Retrieval", status: "succeeded", elapsed_seconds: 4.3 },
    { stage: "Selection", status: "succeeded", elapsed_seconds: 7.2 },
    { stage: "Ranking", status: "succeeded", elapsed_seconds: 4.1 },
    { stage: "Synthesis", status: "succeeded", elapsed_seconds: 3.1 },
  ],
  candidate_pool: rankedPapers.slice(0, 5).map((paper) => makeDiagnosticRow(paper, "retrieval")),
  selection_candidates: rankedPapers
    .slice(0, 5)
    .map((paper, index) => makeDiagnosticRow(paper, "selection", index !== 4)),
  ranked_papers: rankedPapers.slice(0, 5).map((paper) => makeDiagnosticRow(paper, "ranking")),
  final_output: rankedPapers.slice(0, 3).map((paper) => makeDiagnosticRow(paper, "synthesis")),
  warnings: [
    "[Ranking] citation_weight 偏高，可能会提升高引用综述的排序优势。",
    "[Synthesis] 摘要生成超时，已回退本地 evidence summary。",
  ],
};

const graphClusters: GraphCluster[] = [
  {
    id: "cluster-radiology",
    label: "放射学基础模型",
    color: "#d8ddff",
    center: { x: 270, y: 160 },
    radiusX: 170,
    radiusY: 110,
    nodeIds: ["P-00042", "P-00081", "node-llava-med", "node-biomedgpt"],
  },
  {
    id: "cluster-survey",
    label: "医学多模态综述",
    color: "#ffe5c6",
    center: { x: 530, y: 168 },
    radiusX: 150,
    radiusY: 118,
    nodeIds: ["node-mmed-bench", "node-mminfo", "node-medfound"],
  },
  {
    id: "cluster-align",
    label: "多模态对齐与指令微调",
    color: "#ddf3d4",
    center: { x: 790, y: 178 },
    radiusX: 176,
    radiusY: 126,
    nodeIds: ["node-instruction", "node-alignment", "node-vl-align"],
  },
  {
    id: "cluster-chest",
    label: "胸片诊断",
    color: "#dcedff",
    center: { x: 218, y: 408 },
    radiusX: 152,
    radiusY: 108,
    nodeIds: ["P-00118", "node-chexzero", "node-xraygpt"],
  },
  {
    id: "cluster-benchmark",
    label: "检索评测",
    color: "#fff0c6",
    center: { x: 817, y: 408 },
    radiusX: 148,
    radiusY: 104,
    nodeIds: ["P-00167", "node-spar", "node-astabench"],
  },
  {
    id: "cluster-dataset",
    label: "数据集与基准",
    color: "#dbf6ef",
    center: { x: 420, y: 560 },
    radiusX: 188,
    radiusY: 112,
    nodeIds: ["node-mimic", "node-chexpert", "node-slake", "node-padchest"],
  },
  {
    id: "cluster-agent",
    label: "Agent 检索",
    color: "#ffdce8",
    center: { x: 678, y: 566 },
    radiusX: 160,
    radiusY: 116,
    nodeIds: ["P-00192", "node-query-expansion", "node-reranking"],
  },
];

const graphNodes: GraphNode[] = [
  {
    id: "P-00017",
    type: "paper",
    label: "A Survey on Multimodal Large Language Models for Medical Imaging",
    shortLabel: "A Survey on Multimodal LLMs\nfor Medical Imaging",
    x: 520,
    y: 344,
    size: 54,
    clusterId: "center",
    year: 2024,
    highlighted: true,
    meta: {
      authors: "Y. Zhang, L. Han, X. Li, P. Gao, J. Wang, et al.",
      venue: "arXiv preprint",
      citation: 1210,
      doi: "10.48550/arXiv.2404.01067",
      tags: ["Survey", "Multimodal", "LLM", "Medical Imaging", "Review"],
    },
  },
  {
    id: "P-00042",
    type: "paper",
    label: "Med-PaLM M 2",
    x: 302,
    y: 178,
    size: 24,
    clusterId: "cluster-radiology",
    year: 2024,
  },
  {
    id: "P-00081",
    type: "paper",
    label: "RadFM",
    x: 250,
    y: 120,
    size: 18,
    clusterId: "cluster-radiology",
    year: 2023,
  },
  {
    id: "node-llava-med",
    type: "paper",
    label: "LLaVA-Med",
    x: 186,
    y: 208,
    size: 16,
    clusterId: "cluster-radiology",
    year: 2023,
  },
  {
    id: "node-biomedgpt",
    type: "paper",
    label: "BiomedGPT",
    x: 330,
    y: 242,
    size: 15,
    clusterId: "cluster-radiology",
    year: 2023,
  },
  {
    id: "node-mmed-bench",
    type: "paper",
    label: "MMed-Bench",
    x: 490,
    y: 122,
    size: 16,
    clusterId: "cluster-survey",
    year: 2023,
  },
  {
    id: "node-mminfo",
    type: "paper",
    label: "MMInfo",
    x: 564,
    y: 132,
    size: 14,
    clusterId: "cluster-survey",
    year: 2022,
  },
  {
    id: "node-medfound",
    type: "paper",
    label: "MedFound",
    x: 542,
    y: 218,
    size: 15,
    clusterId: "cluster-survey",
    year: 2024,
  },
  {
    id: "node-instruction",
    type: "method",
    label: "Instruction Tuning",
    x: 760,
    y: 166,
    size: 20,
    clusterId: "cluster-align",
  },
  {
    id: "node-alignment",
    type: "method",
    label: "Multimodal Alignment",
    x: 744,
    y: 250,
    size: 18,
    clusterId: "cluster-align",
  },
  {
    id: "node-vl-align",
    type: "method",
    label: "Vision-Language Alignment",
    x: 866,
    y: 212,
    size: 18,
    clusterId: "cluster-align",
  },
  {
    id: "P-00118",
    type: "paper",
    label: "CheXagent",
    x: 184,
    y: 392,
    size: 18,
    clusterId: "cluster-chest",
    year: 2023,
  },
  {
    id: "node-chexzero",
    type: "paper",
    label: "CheXzero",
    x: 258,
    y: 446,
    size: 16,
    clusterId: "cluster-chest",
    year: 2022,
  },
  {
    id: "node-xraygpt",
    type: "paper",
    label: "XrayGPT",
    x: 144,
    y: 486,
    size: 15,
    clusterId: "cluster-chest",
    year: 2023,
  },
  {
    id: "P-00167",
    type: "paper",
    label: "LitSearch",
    x: 808,
    y: 378,
    size: 18,
    clusterId: "cluster-benchmark",
    year: 2024,
  },
  {
    id: "node-spar",
    type: "paper",
    label: "SPAR",
    x: 872,
    y: 418,
    size: 15,
    clusterId: "cluster-benchmark",
    year: 2023,
  },
  {
    id: "node-astabench",
    type: "paper",
    label: "AstaBench",
    x: 782,
    y: 472,
    size: 15,
    clusterId: "cluster-benchmark",
    year: 2024,
  },
  {
    id: "node-mimic",
    type: "dataset",
    label: "MIMIC-CXR",
    x: 334,
    y: 546,
    size: 18,
    clusterId: "cluster-dataset",
    year: 2019,
  },
  {
    id: "node-chexpert",
    type: "dataset",
    label: "CheXpert",
    x: 430,
    y: 544,
    size: 18,
    clusterId: "cluster-dataset",
    year: 2019,
  },
  {
    id: "node-slake",
    type: "dataset",
    label: "SLAKE",
    x: 380,
    y: 620,
    size: 16,
    clusterId: "cluster-dataset",
    year: 2021,
  },
  {
    id: "node-padchest",
    type: "dataset",
    label: "PadChest",
    x: 506,
    y: 602,
    size: 16,
    clusterId: "cluster-dataset",
    year: 2021,
  },
  {
    id: "P-00192",
    type: "paper",
    label: "PaSa",
    x: 668,
    y: 532,
    size: 17,
    clusterId: "cluster-agent",
    year: 2024,
  },
  {
    id: "node-query-expansion",
    type: "method",
    label: "Query Expansion",
    x: 626,
    y: 604,
    size: 15,
    clusterId: "cluster-agent",
  },
  {
    id: "node-reranking",
    type: "method",
    label: "Reranking",
    x: 726,
    y: 598,
    size: 15,
    clusterId: "cluster-agent",
  },
];

const makeEdge = (
  id: string,
  source: string,
  target: string,
  type: GraphEdge["type"] = "association",
  weight = 1,
): GraphEdge => ({
  id,
  source,
  target,
  type,
  weight,
});

const graphEdges: GraphEdge[] = [
  makeEdge("e1", "P-00017", "P-00042", "reference", 3),
  makeEdge("e2", "P-00017", "P-00081", "reference", 3),
  makeEdge("e3", "P-00017", "P-00118", "reference", 2),
  makeEdge("e4", "P-00017", "P-00167", "association", 2),
  makeEdge("e5", "P-00017", "P-00192", "association", 2),
  makeEdge("e6", "P-00017", "node-mmed-bench", "similar", 2),
  makeEdge("e7", "P-00017", "node-medfound", "similar", 2),
  makeEdge("e8", "P-00017", "node-instruction", "association", 1),
  makeEdge("e9", "P-00017", "node-alignment", "association", 1),
  makeEdge("e10", "P-00017", "node-mimic", "association", 1),
  makeEdge("e11", "P-00017", "node-chexpert", "association", 1),
  makeEdge("e12", "P-00017", "node-query-expansion", "association", 1),
  makeEdge("e13", "P-00192", "node-reranking", "association", 1),
  makeEdge("e14", "P-00192", "P-00167", "reference", 1),
  makeEdge("e15", "P-00118", "node-chexzero", "citation-path", 1),
  makeEdge("e16", "P-00118", "node-xraygpt", "similar", 1),
  makeEdge("e17", "P-00042", "node-biomedgpt", "similar", 1),
  makeEdge("e18", "P-00042", "node-vl-align", "association", 1),
];

export const mockGraphResponse: GraphResponse = {
  job_id: mockSearchJob.job_id,
  query: "多模态大模型在医学影像诊断中的研究图谱",
  nodes: graphNodes,
  edges: graphEdges,
  clusters: graphClusters,
  selected_node_id: "P-00017",
  stats: {
    papers: 128,
    authors: 36,
    methods: 18,
    datasets: 11,
    edges: 426,
    clusters: 8,
  },
};

export const mockPaperExplorer: PaperExplorerItem[] = [
  {
    id: "P-00017",
    title: "A Survey on Multimodal Large Language Models for Medical Imaging",
    year: 2024,
    venue: "arXiv",
    authors: "Y. Zhang, L. Han, X. Li, P. Gao, J. Wang, et al.",
    snippet:
      "This survey reviews recent advances in multimodal large language models for medical imaging, including datasets, methods, and future directions.",
  },
  {
    id: "P-00042",
    title: "Med-PaLM M 2: Enhancing Medical Vision-Language Understanding",
    year: 2024,
    venue: "Nature Machine Intelligence",
    authors: "S. Singhal, A. Tu, J. Gottschlich, et al.",
    snippet:
      "Med-PaLM M 2 improves multimodal reasoning in medicine with advanced instruction tuning and alignment.",
  },
  {
    id: "P-00081",
    title: "RadFM: Foundation Model for Radiology",
    year: 2023,
    venue: "Radiology: Artificial Intelligence",
    authors: "H. Chen, D. Dou, Y. Jin, X. Li, R. Xu, et al.",
    snippet:
      "A large-scale radiology foundation model trained on images and reports, demonstrating strong generalization.",
  },
  {
    id: "P-00118",
    title: "CheXagent: Towards a Large Vision-Language Model for Chest X-ray Diagnosis",
    year: 2023,
    venue: "MICCAI",
    authors: "W. Jin, Z. Zhang, Y. Pan, S. Wang, et al.",
    snippet:
      "CheXagent leverages vision-language understanding for accurate and interpretable chest X-ray diagnosis.",
  },
  {
    id: "P-00192",
    title: "PaSa: An LLM Agent for Comprehensive Academic Paper Search",
    year: 2024,
    venue: "arXiv",
    authors: "Q. Zhu, Y. Wang, Y. Shen, H. Huang, et al.",
    snippet:
      "PaSa is an agent framework for comprehensive academic search with query expansion, reranking and evidence path explanation.",
  },
];

export const mockLogs: LogEntry[] = [
  {
    id: "log-1",
    timestamp: "2026-06-30T18:42:10.112Z",
    level: "INFO",
    stage: "query_understanding",
    message: "QueryPlan generated with query_type=survey and time_range=2020-2025",
    raw: { query_type: "survey", methods: ["多模态对齐", "放射学基础模型"] },
  },
  {
    id: "log-2",
    timestamp: "2026-06-30T18:42:12.681Z",
    level: "INFO",
    stage: "retrieval",
    message: "Retrieved 5,642 candidates from 4 providers; deduped to 3,217 papers",
    raw: { candidate_pool: 5642, deduped: 3217 },
  },
  {
    id: "log-3",
    timestamp: "2026-06-30T18:42:14.989Z",
    level: "WARN",
    stage: "selection",
    message: "OpenAlex reference expansion hit provider_time_budget, fallback enabled",
    raw: { provider: "OpenAlex", limit: "provider_time_budget" },
  },
  {
    id: "log-4",
    timestamp: "2026-06-30T18:42:18.221Z",
    level: "INFO",
    stage: "ranking",
    message: "Listwise reranking completed with 50 papers scored",
    raw: { scored: 50 },
  },
  {
    id: "log-5",
    timestamp: "2026-06-30T18:42:20.451Z",
    level: "DEBUG",
    stage: "synthesis",
    message: "Method clusters and citation graph composed for final report",
    raw: { clusters: 8, graph_nodes: 128, graph_edges: 426 },
  },
];

export const mockRecentRuns: SearchJob[] = [
  {
    job_id: "search_20260630_1042",
    status: "succeeded",
    stage: "synthesis",
    progress: 100,
    elapsed_seconds: 18.7,
  },
  {
    job_id: "search_20260630_1016",
    status: "running",
    stage: "retrieval",
    progress: 48,
    elapsed_seconds: 6.2,
  },
  {
    job_id: "search_20260629_2238",
    status: "failed",
    stage: "selection",
    progress: 72,
    elapsed_seconds: 12.1,
    error: "semantic_scholar timeout",
  },
];

export const mockDatasets = [
  "MedEval-2024",
  "AutoScholarQuery_test.jsonl",
  "RealScholarQuery_test.jsonl",
  "LitSearch_Benchmark_v2",
];

export const mockWorkflowStages = [
  { key: "query_understanding", label: "Query Understanding", status: "succeeded", elapsed: 2.1 },
  { key: "query_expansion", label: "Query Expansion", status: "succeeded", elapsed: 1.4 },
  { key: "retrieval", label: "Retrieval", status: "succeeded", elapsed: 4.7 },
  { key: "selection", label: "Selection", status: "succeeded", elapsed: 3.2 },
  { key: "ranking", label: "Ranking", status: "succeeded", elapsed: 5.1 },
  { key: "synthesis", label: "Synthesis", status: "succeeded", elapsed: 2.2 },
] as const;

export const mockPapers = rankedPapers.map((item) => item.paper);

export const mockTopPapers = rankedPapers;
